# .github/workflows/deploy.yml
name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: astro-turnstile-postmark/package-lock.json

      - name: Install deps
        working-directory: ./astro-turnstile-postmark
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-fund --no-audit
          fi

      - name: Build
        working-directory: ./astro-turnstile-postmark
        run: |
          npm run build
          touch dist/.nojekyll   # ensure Pages doesn't try Jekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./astro-turnstile-postmark/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
